openapi: 3.0.1
info:
  title: api test
  version: '1.2'
servers:
  - url: 'http://localhost:8088/'
paths:
  /message:
    get:
      summary: Gets the message
      security:
        - OAuth2: [read]   # require read scope
      responses:
        '200':
          description: OK
        '401':
          description: Not authenticated
        '403':
          description: Access token does not have the required scope
    post:
      summary: create a new message
      security:
        - OAuth2: [write]  # require write scope
      responses:
        '200':
          description: OK
        '401':
          description: Not authenticated
        '403':
          description: Access token does not have the required scope

components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: http://localhost:8000/oauth/authorize
          tokenUrl: http://localhost:8000/oauth/token
          scopes:
            message:read: Grants read access
            message:write: Grants write access
