package com.yubicolabs.PasskeyAuthenticator;

import java.util.Collections;
import java.util.List;

import static org.keycloak.provider.ProviderConfigProperty.STRING_TYPE;

import org.jboss.logging.Logger;
import org.keycloak.Config.Scope;
import org.keycloak.authentication.Authenticator;
import org.keycloak.authentication.AuthenticatorFactory;
import org.keycloak.models.AuthenticationExecutionModel.Requirement;
import org.keycloak.models.AuthenticationExecutionModel;
import org.keycloak.models.KeycloakSession;
import org.keycloak.models.KeycloakSessionFactory;
import org.keycloak.provider.ProviderConfigProperty;

public class PasskeyRegistrationAuthenticatorFactory implements AuthenticatorFactory {

  private static final Authenticator AUTHENTICATOR_INSTANCE = new PasskeyRegistrationAuthenticator();

  public static final String ID = "passkeyregister";

  private static final Logger logger = Logger.getLogger(PasskeyAuthenticatorFactory.class);

  @Override
  public void close() {
    /*
     * @TODO - Autogenerated sub, implement later
     */
  }

  @Override
  public Authenticator create(KeycloakSession keycloakSession) {
    try {
      return AUTHENTICATOR_INSTANCE;
    } catch (Exception e) {
      logger.info("***** Something failed here");
      return AUTHENTICATOR_INSTANCE;
    }
  }

  @Override
  public String getId() {
    return ID;
  }

  @Override
  public void init(Scope arg0) {
    /*
     * @TODO - Autogenerated sub, implement later
     */
  }

  @Override
  public void postInit(KeycloakSessionFactory arg0) {
    /*
     * @TODO - Autogenerated sub, implement later
     */
  }

  @Override
  public String getDisplayType() {
    return "Passkey Registration Authenticator";
  }

  @Override
  public String getReferenceCategory() {
    return null;
  }

  @Override
  public Requirement[] getRequirementChoices() {
    return new AuthenticationExecutionModel.Requirement[] { AuthenticationExecutionModel.Requirement.REQUIRED };
  }

  @Override
  public boolean isConfigurable() {
    return true;
  }

  @Override
  public boolean isUserSetupAllowed() {
    return false;
  }

  @Override
  public List<ProviderConfigProperty> getConfigProperties() {
    ProviderConfigProperty name = new ProviderConfigProperty();

    name.setType(STRING_TYPE);
    name.setName("PK_LABEL_1");
    name.setLabel("Register with a passkey that has been registered");
    name.setHelpText("Passwords are the past, passkeys are the future");

    return Collections.singletonList(name);
  }

  @Override
  public String getHelpText() {
    return "Authenticate with passkey";
  }

}
