/**
 * Shipment configuration constants
 *
 * These values define default behavior for YubiKey shipment orders.
 * Modify these constants to change shipment defaults across the application.
 */

export const SHIPMENT_DEFAULTS = {
  /** Default PIN length for YubiKey pre-registration */
  PIN_LENGTH: 6,

  /** PIN generation type - automatically generated by system */
  PIN_TYPE: 'generate' as const,

  /** Standard delivery type (1 = standard shipping, 2 = express) */
  DELIVERY_TYPE_STANDARD: 1,

  /** Default recipient company name */
  RECIPIENT_COMPANY: 'Yubico',
} as const;
